name: Deploy Rust WASM Synthesizer to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build WASM
      run: |
        wasm-pack build --target web --out-dir pkg --out-name synthesizer

    - name: Prepare deployment directory
      run: |
        mkdir -p deploy
        cp index.html deploy/
        cp -r pkg/ deploy/
        cp -r assets/ deploy/ || true

    - name: Create .nojekyll file
      run: touch deploy/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: deploy/
        retention-days: 30

    - name: Deploy GitHub Pages site
      id: deployment
      uses: actions/deploy-pages@v4